language: node_js

before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

node_js:
  - "10"
  - "12"
  - "13"

jobs:
  include:
  - stage: npm Deployment
    deploy:
      edge: true
      provider: npm
      skip_cleanup: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      on:
        tags: true
